// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1DWlsaxD9kqW598EdQwR1Q_11WG7-F6s',
    appId: '1:137970504611:web:36a4eb6169023511370016',
    messagingSenderId: '137970504611',
    projectId: 'cycling-routes-58601',
    authDomain: 'cycling-routes-58601.firebaseapp.com',
    databaseURL: 'https://cycling-routes-58601-default-rtdb.firebaseio.com',
    storageBucket: 'cycling-routes-58601.appspot.com',
    measurementId: 'G-Q3T0NW8HSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99abCqMd-mKU6Vz6vx6_qPtGH4TMIb0I',
    appId: '1:137970504611:android:4af553d92d62054f370016',
    messagingSenderId: '137970504611',
    projectId: 'cycling-routes-58601',
    databaseURL: 'https://cycling-routes-58601-default-rtdb.firebaseio.com',
    storageBucket: 'cycling-routes-58601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdlo9s1tRQWdgRA6dPRV3CmNHliIX94A0',
    appId: '1:137970504611:ios:8b7e6d76b8c01e52370016',
    messagingSenderId: '137970504611',
    projectId: 'cycling-routes-58601',
    databaseURL: 'https://cycling-routes-58601-default-rtdb.firebaseio.com',
    storageBucket: 'cycling-routes-58601.appspot.com',
    iosClientId: '137970504611-523s5jft1lgc6d41ipdkhlt5cqgr0ih6.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.newsWire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdlo9s1tRQWdgRA6dPRV3CmNHliIX94A0',
    appId: '1:137970504611:ios:cfca2d014b5033a8370016',
    messagingSenderId: '137970504611',
    projectId: 'cycling-routes-58601',
    databaseURL: 'https://cycling-routes-58601-default-rtdb.firebaseio.com',
    storageBucket: 'cycling-routes-58601.appspot.com',
    iosClientId: '137970504611-qrutdpnfprou0oavjs9grn3ro3k8nl9b.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.newsWire.RunnerTests',
  );
}
